posts:
    resource: "@PostsBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:   annotation
    prefix: /dashboard

PostsBundle:
    resource: "@PostsBundle/Resources/config/routing.yml"
    prefix: /blog